                                  
SET foreign_key_checks = 0;

-- COUNTRIES                                
DROP TABLE IF EXISTS `COUNTRY`;
CREATE TABLE `COUNTRY` (
  `ID` INT(11) NOT NULL auto_increment,
  `CODE` VARCHAR(30) NOT NULL,
  `TERM` VARCHAR(100) NOT NULL,
  `DEFINITION` VARCHAR(200),
  `UNIT` VARCHAR(20),
  `TERM_ID` VARCHAR(30),
  PRIMARY KEY  (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- ================================================================================================
-- COUNTRIES
-- ================================================================================================

insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AD', 'Andorra', 'Andorra');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AF', 'Afghanistan', 'Afghanistan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AG', 'Antigua and Barbuda', 'Antigua and Barbuda');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AI', 'Anguilla', 'Anguilla');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AL', 'Albania', 'Albania');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AM', 'Armenia', 'Armenia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AN', 'Netherlands Antilles', 'Netherlands Antilles');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AO', 'Angola', 'Angola');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AQ', 'Antartica', 'Antartica');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AR', 'Argentina', 'Argentina');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AS', 'American Samoa', 'American Samoa');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AT', 'Austria', 'Austria');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AU', 'Australia', 'Australia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AW', 'Aruba', 'Aruba');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AZ', 'Azerbaidjan', 'Azerbaidjan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BA', 'Bosnia Herzegowina', 'Bosnia Herzegowina');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BB', 'Barbados', 'Barbados');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BD', 'Bangladesh', 'Bangladesh');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BE', 'Belgium', 'Belgium');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BF', 'Burkina Faso', 'Burkina Faso');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BG', 'Bulgaria', 'Bulgaria');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BH', 'Bahrain', 'Bahrain');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BI', 'Burundi', 'Burundi');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BJ', 'Benin', 'Benin');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BM', 'Bermuda', 'Bermuda');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BN', 'Brunei Darussalam', 'Brunei Darussalam');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BO', 'Bolivia', 'Bolivia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BR', 'Brazil', 'Brazil');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BS', 'Bahamas', 'Bahamas');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BT', 'Bhutan', 'Bhutan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BV', 'Bouvet Island', 'Bouvet Island');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BW', 'Botswana', 'Botswana');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BY', 'Belarus', 'Belarus');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('BZ', 'Belize', 'Belize');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CA', 'Canada', 'Canada');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CC', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CD', 'Congo, Democratic Republic of', 'Congo, Democratic Republic of (ex-Zaire)');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CF', 'Central African Republic', 'Central African Republic');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CG', 'Congo, People''s Republic of', 'Congo, People''s Republic of');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CH', 'Switzerland', 'Switzerland');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CI', 'Cote d''Ivoire', 'Cote d''Ivoire');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CK', 'Cook Islands', 'Cook Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CL', 'Chile', 'Chile');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CM', 'Cameroon', 'Cameroon');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CN', 'China', 'China');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CO', 'Colombia', 'Colombia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CR', 'Costa Rica', 'Costa Rica');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CU', 'Cuba', 'Cuba');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CV', 'Cape Verde', 'Cape Verde');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CX', 'Christmas Island', 'Christmas Island');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CY', 'Cyprus', 'Cyprus');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('CZ', 'Czech Republic', 'Czech Republic');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('DE', 'Germany', 'Germany');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('DJ', 'Djibouti', 'Djibouti');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('DK', 'Denmark', 'Denmark');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('DM', 'Dominica', 'Dominica');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('DO', 'Dominican Republic', 'Dominican Republic');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('DZ', 'Algeria', 'Algeria');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('EC', 'Ecuador', 'Ecuador');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('EE', 'Estonia', 'Estonia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('EG', 'Egypt', 'Egypt');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('EH', 'Western Sahara', 'Western Sahara');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('ER', 'Eritrea', 'Eritrea');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('ES', 'Spain', 'Spain');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('ET', 'Ethiopia', 'Ethiopia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('FI', 'Finland', 'Finland');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('FJ', 'Fiji', 'Fiji');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('FK', 'Falkland Islands', 'Falkland Islands (Malvinas)');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('FM', 'Micronesia, Federated States of', 'Micronesia, Federated States of');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('FO', 'Faroe Islands', 'Faroe Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('FR', 'France', 'France');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('FX', 'France, Metropolitan', 'France, Metropolitan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GA', 'Gabon', 'Gabon');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GB', 'United Kingdom', 'United Kingdom');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GD', 'Grenada', 'Grenada');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GE', 'Georgia', 'Georgia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GF', 'French Guiana', 'French Guiana');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GH', 'Ghana', 'Ghana');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GI', 'Gibraltar', 'Gibraltar');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GL', 'Greenland', 'Greenland');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GM', 'Gambia', 'Gambia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GN', 'Guinea', 'Guinea');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GP', 'Guadeloupe', 'Guadeloupe');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GQ', 'Equatorial Guinea', 'Equatorial Guinea');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GR', 'Greece', 'Greece');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GS', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GT', 'Guatemala', 'Guatemala');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GU', 'Guam', 'Guam');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GW', 'Guinea-Bissau', 'Guinea-Bissau');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('GY', 'Guyana', 'Guyana');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('HK', 'Hong Kong', 'Hong Kong');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('HM', 'Heard and Mc Donald Islands', 'Heard and Mc Donald Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('HN', 'Honduras', 'Honduras');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('HR', 'Croatia', 'Croatia (local name: Hrvatska)');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('HT', 'Haiti', 'Haiti');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('HU', 'Hungary', 'Hungary');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('ID', 'Indonesia', 'Indonesia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('IE', 'Ireland', 'Ireland');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('IL', 'Israel', 'Israel');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('IN', 'India', 'India');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('IO', 'British Indian Ocean Territory', 'British Indian Ocean Territory');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('IQ', 'Iraq', 'Iraq');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('IR', 'Iran', 'Iran (Islamic Republic of)');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('IS', 'Iceland', 'Iceland');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('IT', 'Italy', 'Italy');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('JM', 'Jamaica', 'Jamaica');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('JO', 'Jordan', 'Jordan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('JP', 'Japan', 'Japan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('KE', 'Kenya', 'Kenya');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('KG', 'Kyrgyzstan', 'Kyrgyzstan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('KH', 'Cambodia', 'Cambodia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('KI', 'Kiribati', 'Kiribati');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('KM', 'Comoros', 'Comoros');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('KN', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('KP', 'Korea, Democratic People''s Republic of', 'Korea, Democratic People''s Republic of');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('KR', 'Korea, Republic of', 'Korea, Republic of');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('KW', 'Kuwait', 'Kuwait');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('KY', 'Cayman Islands', 'Cayman Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('KZ', 'Kazakhstan', 'Kazakhstan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('LA', 'Lao People''s Democratic Republic', 'Lao People''s Democratic Republic');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('LB', 'Lebanon', 'Lebanon');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('LC', 'Saint Lucia', 'Saint Lucia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('LI', 'Liechtenstein', 'Liechtenstein');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('LK', 'Sri Lanka', 'Sri Lanka');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('LR', 'Liberia', 'Liberia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('LS', 'Lesotho', 'Lesotho');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('LT', 'Lithuania', 'Lithuania');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('LU', 'Luxembourg', 'Luxembourg');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('LV', 'Latvia', 'Latvia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('LY', 'Libyan Arab Jamahiriya', 'Libyan Arab Jamahiriya');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MA', 'Morocco', 'Morocco');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MC', 'Monaco', 'Monaco');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MD', 'Moldova, Republic of', 'Moldova, Republic of');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MG', 'Madagascar', 'Madagascar');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MH', 'Marshall Islands', 'Marshall Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MK', 'Macedonia', 'Macedonia, The Former Yugoslav Republic of');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('ML', 'Mali', 'Mali');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MM', 'Myanmar', 'Myanmar');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MN', 'Mongolia', 'Mongolia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MO', 'Macau', 'Macau');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MP', 'Norther Mariana Islands', 'Norther Mariana Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MQ', 'Martinique', 'Martinique');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MR', 'Mauritania', 'Mauritania');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MS', 'Montserrat', 'Montserrat');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MT', 'Malta', 'Malta');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MU', 'Muauritius', 'Muauritius');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MV', 'Maldives', 'Maldives');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MW', 'Malawi', 'Malawi');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MX', 'Mexico', 'Mexico');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MY', 'Malaysia', 'Malaysia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('MZ', 'Mozambique', 'Mozambique');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NA', 'Namibia', 'Namibia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NC', 'New Caledonia', 'New Caledonia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NE', 'Niger', 'Niger');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NF', 'Norfolk Island', 'Norfolk Island');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NG', 'Nigeria', 'Nigeria');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NI', 'Nicaragua', 'Nicaragua');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NL', 'Netherlands', 'Netherlands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NO', 'Norway', 'Norway');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NP', 'Nepal', 'Nepal');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NR', 'Nauru', 'Nauru');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NU', 'Niue', 'Niue');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('NZ', 'New Zealand', 'New Zealand');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('OM', 'Oman', 'Oman');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PA', 'Panama', 'Panama');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PE', 'Peru', 'Peru');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PF', 'French Polynesia', 'French Polynesia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PG', 'Papua New Guinea', 'Papua New Guinea');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PH', 'Philippines', 'Philippines');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PK', 'Pakistan', 'Pakistan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PL', 'Poland', 'Poland');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PM', 'St. Pierre and Miquelon', 'St. Pierre and Miquelon');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PN', 'Pitcairn Islands', 'Pitcairn, Henderson, Ducie and Oeno Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PR', 'Puerto Rico', 'Puerto Rico');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PS', 'Palestinian Territory', 'Palestinian Territory');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PT', 'Portugal', 'Portugal');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PW', 'Palau', 'Palau');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('PY', 'Paraguay', 'Paraguay');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('QA', 'Qatar', 'Qatar');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('RE', 'Reunion', 'Reunion');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('RO', 'Romania', 'Romania');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('RU', 'Russian Federation', 'Russian Federation');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('RW', 'Rwanda', 'Rwanda');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SA', 'Saudi Arabia', 'Saudi Arabia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SB', 'Solomon Islands', 'Solomon Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SC', 'Seychelles', 'Seychelles');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SD', 'Sudan', 'Sudan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SE', 'Sweden', 'Sweden');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SG', 'Singapore', 'Singapore');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SH', 'St. Helena', 'St. Helena');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SI', 'Slovenia', 'Slovenia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SJ', 'Svalbard and Jan Mayen Islands', 'Svalbard and Jan Mayen Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SK', 'Slovakia', 'Slovakia (Slovak Republic)');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SL', 'Sierra Leone', 'Sierra Leone');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SM', 'San Marino', 'San Marino');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SN', 'Senegal', 'Senegal');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SO', 'Somalia', 'Somalia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SR', 'Suriname', 'Suriname');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('ST', 'Sao Tome and Principe', 'Sao Tome and Principe');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SV', 'El Salvador', 'El Salvador');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SY', 'Syrian Arab Republic', 'Syrian Arab Republic');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('SZ', 'Swaziland', 'Swaziland');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TC', 'Turks and Caicos Islands', 'Turks and Caicos Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TD', 'Chad', 'Chad');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TF', 'French Southern Territories', 'French Southern Territories');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TG', 'Togo', 'Togo');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TH', 'Thailand', 'Thailand');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TJ', 'Tajikistan', 'Tajikistan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TK', 'Tokelau', 'Tokelau');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TL', 'East Timor', 'East Timor');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TM', 'Turkmenistan', 'Turkmenistan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TN', 'Tunisia', 'Tunisia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TO', 'Tonga', 'Tonga');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TR', 'Turkey', 'Turkey');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TT', 'Trinidad and Tobago', 'Trinidad and Tobago');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TV', 'Tuvalu', 'Tuvalu');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TW', 'Taiwan', 'Taiwan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('TZ', 'Tanzania, United Republic of', 'Tanzania, United Republic of');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('UA', 'Ukraine', 'Ukraine');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('UG', 'Uganda', 'Uganda');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('AE', 'United Arab Emirates', 'United Arab Emirates');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('UM', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('US', 'United States of America', 'United States of America');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('UY', 'Uruguay', 'Uruguay');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('UZ', 'Uzbekistan', 'Uzbekistan');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('VA', 'Vatican City State (Holy See)', 'Vatican City State (Holy See)');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('VC', 'Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('VE', 'Venezuela', 'Venezuela');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('VG', 'Virgin Islands (British)', 'Virgin Islands (British)');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('VI', 'Virgin Islands (U.S.)', 'Virgin Islands (U.S.)');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('VN', 'Vietnam', 'Vietnam');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('VU', 'Vanuatu', 'Vanuatu');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('WF', 'Wallis and Futuna Islands', 'Wallis and Futuna Islands');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('WS', 'Samoa', 'Samoa');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('YE', 'Yemen', 'Yemen');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('YT', 'Mayotte', 'Mayotte');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('YU', 'Serbia and Montenegro', 'Serbia and Montenegro');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('ZA', 'South Africa', 'South Africa');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('ZM', 'Zambia', 'Zambia');
insert into COUNTRY (CODE, TERM, DEFINITION) VALUES ('ZW', 'Zimbabwe', 'Zimbabwe');


-- ================================================================

SET foreign_key_checks = 1;

-- INDEX
CREATE UNIQUE INDEX INDEX_COUNTRY_VAL ON COUNTRY (CODE);

